exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"


keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Base URL of site. It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
# baseurl: "/" # the subpath of your site
url: "https://mkgmarketinginc.com" # the base hostname & protocol for your site
cover: "/assets/cover.png"
logo: "/assets/logo.png"

permalink: /:collection/:path/

# Build settings
markdown: kramdown

# Category descriptions (for archive pages)
descriptions:
  - cat: blog
    desc: "Blog posts about industry and MKG news"
  - category: seo
    desc: "Blog posts about search engine optimization"
  - category: ppc
    desc: "Blog posts about pay-per-click"
  - category: analytics
    desc: "Blog posts about analytics"
  - category: job
    desc: "Blog posts about jobs"
  - category: podcast
    desc: "Blog posts about Hard Question Podcasts"

plugins:
   - jekyll-feed
   - jekyll-sitemap
